class PaymentStatus:
    PENDING = "PENDING"
    SUCCESS = "PAID"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ShippingStatus:
    PENDING = "PENDING"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    RETURNED = "RETURNED"
